---
driver:
  name: vagrant
  synced_folders:
   - ["./results", "/tmp/results"]
  network:
    - ["private_network", {ip: "192.168.33.198"}]

provisioner:
  name: shell

verifier:
  name: inspec

platforms:
  # - name: centos-7
  - name: centos-7.5

suites:
  - name: base
    provisioner:
      arguments: ["<%= ENV['HAB_ORIGIN'] %>", "chef-base"]
      always_update_cookbooks: true
      client_rb:
        data_collector.server_url: 'https://192.168.33.199/data-collector/v0/'
        data_collector.token: '<your token>'
        verify_api_cert: false
        ssl_verify_mode: :verify_none
      verifier:
        inspect_tests:
          test/integration/base

